### ISSUE TITLE
Getting an OverflowError (w/ python3)

### ISSUE THREAD

**Issue by pft** [royvegard/Nano-Basket#10]
> Traceback (most recent call last):
>   File "/home/me/Sources/Nano-Basket/./nano_basket_backend.py", line 501, in <module>
>     Midi_Comm = NanoKontrolAlsaMidiComm()
>   File "/home/me/Sources/Nano-Basket/./nano_basket_backend.py", line 269, in __init__
>     self.event = alsaseq.SeqEvent(alsaseq.SEQ_EVENT_SYSEX)
> OverflowError: Python int too large to convert to C long

**Comment by pft** [comment]
Looks like a python-pyalsa bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979559
