### ISSUE TITLE
Python int too Large to fit into C Long

### ISSUE THREAD

**Issue by TsunamiMommy** [royvegard/Nano-Basket#11]
I was trying to use your package to control my Korg NanoKontrol control surface and hit a little snag. I am trying to use it with Python 3 but I get the following error. I was launching it with command `python3 nano_basket_main.py`
System libraries are up to date and I have pyalsa and PyGObject installed.
```
Traceback (most recent call last):
  File "/home/daniel/configs/Nano-Basket/./nano_basket_main.py", line 33, in <module>
    Midi_Device = NanoKontrolAlsaMidiComm()
  File "/home/daniel/configs/Nano-Basket/nano_basket_backend.py", line 269, in __init__
    self.event = alsaseq.SeqEvent(alsaseq.SEQ_EVENT_SYSEX)
OverflowError: Python int too large to convert to C long
```

**Comment by xintrea** [comment]
Same error. The error line is:
```
self.event = alsaseq.SeqEvent(alsaseq.SEQ_EVENT_SYSEX)
```
I'm append debug line:
```
print( "alsaseq.SEQ_EVENT_SYSEX: "+str( int(alsaseq.SEQ_EVENT_SYSEX) ) )
self.event = alsaseq.SeqEvent(alsaseq.SEQ_EVENT_SYSEX)
```
And get error:
```
$ python3 nano_basket_main.py
alsaseq.SEQ_EVENT_SYSEX: 315701287920557015231746469374140126848057806069433848520996442474077896118040280446827322192982778036935991159410458088858621034602855901831822090957249542454035237858266532406423746184667355646341406675495075296391155014596564577965062354643694753177171515765177344558231920888521336526729754327947612995730269459443629344404521191593403054625932096029258892212307592584049828939880259535763835214469305539836356735613249869911228799956675651622554103861445770814010219159244073507745648250000703350024591332758344364473173395846008868365451882145158578760695509550271688630463095098506898511291039425221333233770177236986045725391119505595248036570982953411623711955801825920921027729570846982511715262600778524621353825145851496489531652828983288054163031843801030412392727901417489077610047264934408166150555940608201872856407413511206173359083516070311558391028193972003488720183479039068178427806738027344778747038954436492511107004297589672250208699482162966403307666332800689253877198682790903233244322329549194860352982466072296480580866480878732354410609338974360551261336806132939982418266558599954613684533679936688065640543177104082203941847816956336839338
Traceback (most recent call last):
  File "/home/xi/work/develop/python/korgNanoControlMidi/Nano-Basket/nano_basket_main.py", line 33, in <module>
    Midi_Device = NanoKontrolAlsaMidiComm()
  File "/home/xi/work/develop/python/korgNanoControlMidi/Nano-Basket/nano_basket_backend.py", line 270, in __init__
    self.event = alsaseq.SeqEvent(alsaseq.SEQ_EVENT_SYSEX)
OverflowError: Python int too large to convert to C long
```

**Comment by nomadbyte** [comment]
Update to `pyalsa-1.2.7`. Discussed earlier, see #10 and #7
