### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by v322v322** [royvegard/Nano-Basket#14]
When I attempt to run nano-basket to control my original Korg NanoKontrol, I get the following error:

Traceback (most recent call last):
  File "/usr/local/lib/nano-basket/./nano_basket_main.py", line 33, in <module>
    Midi_Device = NanoKontrolAlsaMidiComm()
  File "/usr/local/lib/nano-basket/nano_basket_backend.py", line 269, in __init__
    self.event = alsaseq.SeqEvent(alsaseq.SEQ_EVENT_SYSEX)
OverflowError: Python int too large to convert to C long

This is using Python 3.10.12 on Linux Mint 21.2. PyGObject is version 3.42.1, and pyalsa is version 1.1.6.

**Comment by royvegard** [comment]
See issue #11 
Others have solved this by upgrading pyalsa to version 1.2.7 or higher.
